"""Management command to restore database and media from backup bundles."""

from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path
from typing import Any

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    """Restore database fixture and media archive created by backup_data."""

    help = "Restore database and media from a backup directory generated by backup_data."

    def add_arguments(self, parser) -> None:
        parser.add_argument("backup_path", help="Path to backup directory (contains manifest.json).")
        parser.add_argument(
            "--database-only",
            action="store_true",
            help="Restore only database fixture.",
        )
        parser.add_argument(
            "--media-only",
            action="store_true",
            help="Restore only media archive.",
        )
        parser.add_argument(
            "--keep-media",
            action="store_true",
            help="Do not clear current MEDIA_ROOT before extraction.",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help="Skip interactive confirmation prompt.",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        database_only = bool(options.get("database_only"))
        media_only = bool(options.get("media_only"))
        if database_only and media_only:
            raise CommandError("Cannot combine --database-only and --media-only.")

        restore_database = not media_only
        restore_media = not database_only

        backup_path_raw = str(options.get("backup_path") or "").strip()
        backup_dir = Path(backup_path_raw).resolve()
        if not backup_dir.exists() or not backup_dir.is_dir():
            raise CommandError(f"Backup path does not exist or is not a directory: {backup_dir}")

        manifest = self._read_manifest(backup_dir)

        database_fixture_path = None
        if restore_database:
            database_fixture_name = str(manifest.get("database_file") or "database.json").strip()
            if not database_fixture_name:
                raise CommandError("Manifest missing database_file and database restore was requested.")
            database_fixture_path = backup_dir / database_fixture_name
            if not database_fixture_path.exists():
                raise CommandError(f"Database fixture not found: {database_fixture_path}")

        media_archive_path = None
        if restore_media:
            media_archive_name = str(manifest.get("media_file") or "media.zip").strip()
            if not media_archive_name:
                raise CommandError("Manifest missing media_file and media restore was requested.")
            media_archive_path = backup_dir / media_archive_name
            if not media_archive_path.exists():
                raise CommandError(f"Media archive not found: {media_archive_path}")

        if not options.get("force") and options.get("interactive", True):
            self.stdout.write(self.style.WARNING("This operation will overwrite current data."))
            answer = input("Type 'yes' to continue: ").strip().lower()
            if answer != "yes":
                raise CommandError("Restore cancelled by user.")

        if restore_database and database_fixture_path is not None:
            call_command("flush", interactive=False, verbosity=0)
            call_command("loaddata", str(database_fixture_path), verbosity=0)

        if restore_media and media_archive_path is not None:
            media_root = Path(getattr(settings, "MEDIA_ROOT", "")).resolve()
            media_root.mkdir(parents=True, exist_ok=True)
            if not options.get("keep_media"):
                self._clear_directory(media_root)
            self._safe_extract_zip(media_archive_path=media_archive_path, target_dir=media_root)

        self.stdout.write(self.style.SUCCESS("Restore completed successfully."))

    def _read_manifest(self, backup_dir: Path) -> dict[str, Any]:
        manifest_path = backup_dir / "manifest.json"
        if not manifest_path.exists():
            return {}
        try:
            raw = manifest_path.read_text(encoding="utf-8")
            data = json.loads(raw)
        except Exception as exc:
            raise CommandError(f"Unable to read manifest.json: {exc}") from exc
        if not isinstance(data, dict):
            raise CommandError("manifest.json must contain an object.")
        return data

    def _clear_directory(self, directory: Path) -> None:
        for item in directory.iterdir():
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink(missing_ok=True)

    def _safe_extract_zip(self, *, media_archive_path: Path, target_dir: Path) -> None:
        target_root = target_dir.resolve()
        with zipfile.ZipFile(media_archive_path, mode="r") as archive:
            for member in archive.infolist():
                destination = (target_root / member.filename).resolve()
                if not str(destination).startswith(str(target_root)):
                    raise CommandError("Unsafe media archive path detected.")
            archive.extractall(target_root)
