"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import pymysql

try:
    import dj_database_url
except Exception:
    dj_database_url = None

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def _load_env_file(path: Path) -> None:
    """Load KEY=VALUE pairs into process environment without overriding existing variables."""
    if not path.is_file():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue

        cleaned_value = value.strip().strip('"').strip("'")
        os.environ[key] = cleaned_value


for env_file in (
    PROJECT_ROOT / ".env.local",
    PROJECT_ROOT / ".env",
    BASE_DIR / ".env.local",
    BASE_DIR / ".env",
):
    _load_env_file(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-s%cqxemq154@0f3m&ry8ec5#e^=9s3wpt!tg58wxthkt1!y3^9')

# SECURITY WARNING: don't run with debug turned on in production!
IS_RENDER = bool(str(os.environ.get("RENDER", "")).strip())
DEBUG = os.environ.get('DEBUG', 'false' if IS_RENDER else 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'corsheaders'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'app.middleware.RequestIDLoggingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.RoleBasedAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_EXPOSE_HEADERS = ["X-Request-ID"]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# MySQL database configuration (values loaded from environment variables).

_database_url = str(os.environ.get("DATABASE_URL", "")).strip()
if _database_url and dj_database_url is not None:
    DATABASES = {
        "default": dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
            'NAME': os.environ.get('DB_NAME', 'moviebooking'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'root123'),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    }




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# eSewa (ePay V2) configuration
ESEWA_PRODUCT_CODE = os.environ.get("ESEWA_PRODUCT_CODE", "EPAYTEST").strip() or "EPAYTEST"
ESEWA_SECRET_KEY = os.environ.get("ESEWA_SECRET_KEY", "8gBm/:&EnhH.1/q").strip() or "8gBm/:&EnhH.1/q"
ESEWA_FORM_URL = os.environ.get(
    "ESEWA_FORM_URL",
    "https://rc-epay.esewa.com.np/api/epay/main/v2/form",
).strip() or "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
ESEWA_STATUS_CHECK_URL = os.environ.get(
    "ESEWA_STATUS_CHECK_URL",
    "https://rc.esewa.com.np/api/epay/transaction/status/",
).strip() or "https://rc.esewa.com.np/api/epay/transaction/status/"
try:
    ESEWA_PENDING_TTL_SECONDS = int(os.environ.get("ESEWA_PENDING_TTL_SECONDS", "1800"))
except (TypeError, ValueError):
    ESEWA_PENDING_TTL_SECONDS = 1800
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173").strip() or "http://localhost:5173"


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}

def _env_non_negative_int(name: str, default: int) -> int:
    raw = os.environ.get(name, str(default))
    try:
        parsed = int(raw)
    except (TypeError, ValueError):
        parsed = int(default)
    return max(parsed, 0)


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, str(default))
    try:
        return int(raw)
    except (TypeError, ValueError):
        return int(default)


def _env_str(name: str, default: str) -> str:
    value = str(os.environ.get(name, default) or "").strip()
    return value if value else str(default)


CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", True)
    
# Ticket validation API rate limiting (per minute)
TICKET_VALIDATION_SCAN_RATE_LIMIT_STAFF_PER_MINUTE = _env_non_negative_int(
    "TICKET_VALIDATION_SCAN_RATE_LIMIT_STAFF_PER_MINUTE",
    60,
)
TICKET_VALIDATION_SCAN_RATE_LIMIT_IP_PER_MINUTE = _env_non_negative_int(
    "TICKET_VALIDATION_SCAN_RATE_LIMIT_IP_PER_MINUTE",
    120,
)
TICKET_VALIDATION_MONITOR_RATE_LIMIT_STAFF_PER_MINUTE = _env_non_negative_int(
    "TICKET_VALIDATION_MONITOR_RATE_LIMIT_STAFF_PER_MINUTE",
    120,
)
TICKET_VALIDATION_MONITOR_RATE_LIMIT_IP_PER_MINUTE = _env_non_negative_int(
    "TICKET_VALIDATION_MONITOR_RATE_LIMIT_IP_PER_MINUTE",
    240,
)


# Cache backend configuration (Redis in scale environments).
_cache_backend = str(os.environ.get("CACHE_BACKEND", "redis")).strip().lower()
_redis_url = str(os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")).strip() or "redis://127.0.0.1:6379/1"
_cache_timeout = max(_env_int("CACHE_DEFAULT_TIMEOUT_SECONDS", 300), 30)
if _cache_backend in {"redis", "django-redis"}:
    try:
        import redis  # noqa: F401
    except Exception:
        _cache_backend = "locmem"

if _cache_backend in {"redis", "django-redis"}:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
            "TIMEOUT": _cache_timeout,
            "KEY_PREFIX": str(os.environ.get("CACHE_KEY_PREFIX", "mt")).strip() or "mt",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "mero-ticket-local-cache",
            "TIMEOUT": _cache_timeout,
            "KEY_PREFIX": str(os.environ.get("CACHE_KEY_PREFIX", "mt")).strip() or "mt",
        }
    }


# Cookie-based auth session configuration.
APP_AUTH_COOKIE_ENABLED = _env_bool("APP_AUTH_COOKIE_ENABLED", True)
APP_AUTH_ACCESS_COOKIE_NAME = _env_str("APP_AUTH_ACCESS_COOKIE_NAME", "mt_access_token")
APP_AUTH_REFRESH_COOKIE_NAME = _env_str("APP_AUTH_REFRESH_COOKIE_NAME", "mt_refresh_token")
APP_AUTH_COOKIE_PATH = _env_str("APP_AUTH_COOKIE_PATH", "/")
_auth_cookie_domain = str(os.environ.get("APP_AUTH_COOKIE_DOMAIN", "")).strip()
APP_AUTH_COOKIE_DOMAIN = _auth_cookie_domain or None
APP_AUTH_COOKIE_SECURE = _env_bool("APP_AUTH_COOKIE_SECURE", not DEBUG)
_auth_cookie_samesite = _env_str("APP_AUTH_COOKIE_SAMESITE", "Lax").capitalize()
APP_AUTH_COOKIE_SAMESITE = _auth_cookie_samesite if _auth_cookie_samesite in {"Lax", "Strict", "None"} else "Lax"

# Set session and token expiry to 1 hour (3600 seconds)
APP_AUTH_ACCESS_TOKEN_MAX_AGE_SECONDS = 60 * 60  # 1 hour
APP_AUTH_REFRESH_TOKEN_MAX_AGE_SECONDS = max(
    _env_int("APP_AUTH_REFRESH_TOKEN_MAX_AGE_SECONDS", 60 * 60 * 24 * 30),
    60,
)

# Django session expiry (1 hour)
SESSION_COOKIE_AGE = 60 * 60  # 1 hour


# Email settings (used for OTP/reset and notifications)
_has_smtp_credentials = bool(os.environ.get("EMAIL_HOST_USER", "").strip()) and bool(
    os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
)
_default_email_backend = (
    "django.core.mail.backends.smtp.EmailBackend"
    if (not DEBUG or _has_smtp_credentials)
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    _default_email_backend,
).strip() or _default_email_backend
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip() or "smtp.gmail.com"
try:
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
except (TypeError, ValueError):
    EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
_configured_default_from_email = os.environ.get("DEFAULT_FROM_EMAIL", "").strip()
DEFAULT_FROM_EMAIL = (
    _configured_default_from_email
    or EMAIL_HOST_USER
    or "noreply@meroticket.local"
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "app.logging_utils.RequestContextFilter",
        },
    },
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s request_id=%(request_id)s %(message)s",
        },
        "request": {
            "format": (
                "%(asctime)s %(levelname)s %(name)s "
                "request_id=%(request_id)s method=%(method)s path=%(path)s "
                "status=%(status_code)s duration_ms=%(duration_ms)s "
                "user_id=%(user_id)s ip=%(client_ip)s %(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_context"],
            "formatter": "default",
        },
        "request_console": {
            "class": "logging.StreamHandler",
            "filters": ["request_context"],
            "formatter": "request",
        },
    },
    "loggers": {
        "app.request": {
            "handlers": ["request_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
