from django.urls import path
from . import views

urlpatterns = [
    path('auth/register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/slides/', views.home_slides, name='home-slides'),
    path('home/collaborators/', views.home_collaborators, name='home-collaborators'),
    path('admin/home-slides/', views.admin_home_slides, name='admin-home-slides'),
    path('admin/home-slides/<int:slide_id>/', views.admin_home_slide_detail, name='admin-home-slide-detail'),
    path('admin/home-slides/<int:slide_id>/toggle/', views.admin_home_slide_toggle, name='admin-home-slide-toggle'),
    path('admin/collaborators/', views.admin_collaborators, name='admin-collaborators'),
    path('admin/collaborators/<int:collaborator_id>/', views.admin_collaborator_detail, name='admin-collaborator-detail'),
    path('admin/collaborators/<int:collaborator_id>/toggle/', views.admin_collaborator_toggle, name='admin-collaborator-toggle'),
    path('admin/vendors/', views.manage_vendors, name='admin-vendors'),
    path('cinemas/', views.list_cinemas, name='cinema-list'),
    path('movies/', views.movies, name='movie-list'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie-detail'),
    path('shows/', views.shows, name='show-list'),
    path('shows/<int:show_id>/', views.show_detail, name='show-detail'),
    path('auth/forgot-password/', views.forgot_password, name='forgot-password'),
    path('auth/verify-otp/', views.verify_otp, name='verify-otp'),
    path('auth/reset-password/', views.reset_password, name='reset-password'),
    path('profile/<int:user_id>/', views.update_profile, name='profile-update'),
    path('profile/admin/<int:admin_id>/', views.update_admin_profile, name='admin-profile-update'),
    path('profile/vendor/<int:vendor_id>/', views.update_vendor_profile, name='vendor-profile-update'),
    path('payment/qr/', views.create_payment_qr, name='payment-qr'),
    path('ticket/<str:reference>/download/', views.download_ticket, name='ticket-download'),
    path('ticket/<str:reference>/details/', views.ticket_details, name='ticket-details'),
]
