"""URL configuration for app API endpoints."""

from __future__ import annotations

from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views
from .views.bookings import (
    vendor_booking_cancel,
    vendor_booking_delete,
    vendor_booking_detail,
    vendor_booking_mark_complete,
    vendor_booking_refund,
    vendor_bookings,
    vendor_bulk_assign_booking_seats,
)
from .viewsets import MovieAdminViewSet, MovieCreditViewSet, PersonViewSet, ReviewViewSet

router = DefaultRouter()
router.register(r"admin/movies", MovieAdminViewSet, basename="admin-movies")
router.register(r"people", PersonViewSet, basename="people")
router.register(r"movie-credits", MovieCreditViewSet, basename="movie-credits")
router.register(r"reviews", ReviewViewSet, basename="reviews")

urlpatterns = [
    path('auth/register/', views.register, name='register'),
    path('auth/register/request-otp/', views.register_request_otp, name='register-request-otp'),
    path('auth/register/verify-otp/', views.register_verify_otp, name='register-verify-otp'),
    path('auth/login/', views.login, name='auth-login'),
    path('auth/refresh/', views.refresh, name='auth-refresh'),
    path('auth/logout/', views.logout, name='auth-logout'),
    path('login/', views.login, name='login'),
    path('banners/', views.banners, name='banner-list'),
    path('banners/active/', views.active_banners, name='banner-active'),
    path('admin/banners/', views.admin_banners, name='admin-banners'),
    path('admin/banners/<int:banner_id>/', views.admin_banner_detail, name='admin-banner-detail'),
    path('home/slides/', views.home_slides, name='home-slides'),
    path('home/now-showing-slides/', views.home_now_showing_slides, name='home-now-showing-slides'),
    path('home/collaborators/', views.home_collaborators, name='home-collaborators'),
    path('admin/home-slides/', views.admin_home_slides, name='admin-home-slides'),
    path('admin/home-slides/<int:slide_id>/', views.admin_home_slide_detail, name='admin-home-slide-detail'),
    path('admin/home-slides/<int:slide_id>/toggle/', views.admin_home_slide_toggle, name='admin-home-slide-toggle'),
    path('admin/collaborators/', views.admin_collaborators, name='admin-collaborators'),
    path('admin/collaborators/<int:collaborator_id>/', views.admin_collaborator_detail, name='admin-collaborator-detail'),
    path('admin/collaborators/<int:collaborator_id>/toggle/', views.admin_collaborator_toggle, name='admin-collaborator-toggle'),
    path('admin/vendors/', views.manage_vendors, name='admin-vendors'),
    path('admin/users/', views.admin_users, name='admin-users'),
    path('admin/users/<int:user_id>/', views.admin_user_detail, name='admin-user-detail'),
    path('admin/bookings/', views.admin_bookings, name='admin-bookings'),
    path('admin/analytics/dropoffs/', views.admin_booking_dropoff_analytics, name='admin-booking-dropoff-analytics'),
    path('admin/revenue/config/', views.admin_revenue_config, name='admin-revenue-config'),
    path('admin/revenue/analytics/', views.admin_revenue_analytics, name='admin-revenue-analytics'),
    path('admin/revenue/transactions/', views.admin_revenue_transactions, name='admin-revenue-transactions'),
    path('admin/revenue/reports/', views.admin_revenue_report, name='admin-revenue-reports'),
    path('admin/bookings/<int:booking_id>/', views.admin_booking_detail, name='admin-booking-detail'),
    path('admin/bookings/<int:booking_id>/status/complete/', views.admin_booking_mark_complete, name='admin-booking-mark-complete'),
    path('admin/bookings/<int:booking_id>/cancel/', views.admin_booking_cancel, name='admin-booking-cancel'),
    path('admin/bookings/<int:booking_id>/refund/', views.admin_booking_refund, name='admin-booking-refund'),
    path('admin/coupons/', views.admin_coupons, name='admin-coupons'),
    path('admin/coupons/<int:coupon_id>/', views.admin_coupon_detail, name='admin-coupon-detail'),
    path('admin/pricing-rules/', views.admin_pricing_rules, name='admin-pricing-rules'),
    path('admin/pricing-rules/<int:rule_id>/', views.admin_pricing_rule_detail, name='admin-pricing-rule-detail'),
    path('admin/withdrawals/', views.admin_withdrawal_requests, name='admin-withdrawal-requests'),
    path('admin/withdrawals/<int:transaction_id>/approve/', views.admin_withdrawal_approve, name='admin-withdrawal-approve'),
    path('admin/withdrawals/<int:transaction_id>/reject/', views.admin_withdrawal_reject, name='admin-withdrawal-reject'),
    path('admin/withdrawals/<int:transaction_id>/retry/', views.admin_withdrawal_retry, name='admin-withdrawal-retry'),
    path('admin/loyalty/rules/', views.admin_loyalty_rule, name='admin-loyalty-rule'),
    path('admin/loyalty/rewards/', views.admin_loyalty_rewards, name='admin-loyalty-rewards'),
    path('admin/loyalty/rewards/<int:reward_id>/', views.admin_loyalty_reward_detail, name='admin-loyalty-reward-detail'),
    path('admin/loyalty/promotions/', views.admin_loyalty_promotions, name='admin-loyalty-promotions'),
    path('admin/loyalty/promotions/<int:promotion_id>/', views.admin_loyalty_promotion_detail, name='admin-loyalty-promotion-detail'),
    path('admin/subscriptions/plans/', views.admin_subscription_plans, name='admin-subscription-plans'),
    path('admin/subscriptions/plans/<int:plan_id>/', views.admin_subscription_plan_detail, name='admin-subscription-plan-detail'),
    path('admin/referrals/', views.admin_referral_controls, name='admin-referral-controls'),
    path('admin/referrals/<int:referral_id>/status/', views.admin_referral_status, name='admin-referral-status'),
    path('vendor/bookings/', vendor_bookings, name='vendor-bookings'),
    path('vendor/bookings/<int:booking_id>/', vendor_booking_detail, name='vendor-booking-detail'),
    path('vendor/bookings/<int:booking_id>/status/complete/', vendor_booking_mark_complete, name='vendor-booking-mark-complete'),
    path('vendor/bookings/<int:booking_id>/bulk-assign-seats/', vendor_bulk_assign_booking_seats, name='vendor-booking-bulk-assign-seats'),
    path('vendor/bookings/<int:booking_id>/cancel/', vendor_booking_cancel, name='vendor-booking-cancel'),
    path('vendor/bookings/<int:booking_id>/refund/', vendor_booking_refund, name='vendor-booking-refund'),
    path('vendor/bookings/<int:booking_id>/delete/', vendor_booking_delete, name='vendor-booking-delete'),
    path('bookings/history/', views.customer_bookings, name='customer-bookings'),
    path('bookings/history/<int:booking_id>/', views.customer_booking_detail, name='customer-booking-detail'),
    path('bookings/history/<int:booking_id>/cancel/', views.customer_booking_cancel, name='customer-booking-cancel'),
    path('loyalty/dashboard/', views.loyalty_dashboard, name='loyalty-dashboard'),
    path('loyalty/transactions/', views.loyalty_transactions, name='loyalty-transactions'),
    path('loyalty/rewards/', views.loyalty_rewards, name='loyalty-rewards'),
    path('loyalty/rewards/redeem/', views.loyalty_redeem_reward, name='loyalty-reward-redeem'),
    path('loyalty/redemptions/', views.loyalty_redemptions, name='loyalty-redemptions'),
    path('loyalty/checkout/preview/', views.loyalty_checkout_preview, name='loyalty-checkout-preview'),
    path('loyalty/referral/bonus/', views.loyalty_referral_bonus, name='loyalty-referral-bonus'),
    path('subscriptions/plans/', views.subscription_plans, name='subscription-plans'),
    path('subscriptions/plans/<int:plan_id>/', views.subscription_plan_detail, name='subscription-plan-detail'),
    path('subscriptions/dashboard/', views.subscription_dashboard, name='subscription-dashboard'),
    path('subscriptions/active/', views.subscription_active, name='subscription-active'),
    path('subscriptions/subscribe/', views.subscription_subscribe, name='subscription-subscribe'),
    path('subscriptions/upgrade/', views.subscription_upgrade, name='subscription-upgrade'),
    path('subscriptions/cancel/', views.subscription_cancel, name='subscription-cancel'),
    path('subscriptions/renew/', views.subscription_renew, name='subscription-renew'),
    path('subscriptions/pause/', views.subscription_pause, name='subscription-pause'),
    path('subscriptions/resume/', views.subscription_resume, name='subscription-resume'),
    path('subscriptions/checkout/preview/', views.subscription_checkout_preview, name='subscription-checkout-preview'),
    path('user/subscription/', views.user_subscription, name='user-subscription'),
    path('referral/dashboard/', views.referral_dashboard, name='referral-dashboard'),
    path('referral/wallet/transactions/', views.referral_wallet_transactions, name='referral-wallet-transactions'),
    path('referral/wallet/preview/', views.referral_wallet_checkout_preview, name='referral-wallet-preview'),
    path('user/wallet/', views.user_wallet, name='user-wallet'),
    path('user/wallet/booking/pay/', views.user_wallet_booking_pay, name='user-wallet-booking-pay'),
    path('user/wallet/topup/esewa/initiate/', views.user_wallet_topup_esewa_initiate, name='user-wallet-topup-esewa-initiate'),
    path('user/wallet/topup/esewa/verify/', views.user_wallet_topup_esewa_verify, name='user-wallet-topup-esewa-verify'),
    path('user/wallet/topup/esewa/callback/success/', views.user_wallet_topup_esewa_callback_success, name='user-wallet-topup-esewa-callback-success'),
    path('user/wallet/topup/esewa/callback/failure/', views.user_wallet_topup_esewa_callback_failure, name='user-wallet-topup-esewa-callback-failure'),
    path('user/redeem/', views.user_redeem, name='user-redeem'),
    path('user/offers/', views.user_vendor_offers, name='user-vendor-offers'),
    path('group-booking/sessions/', views.group_booking_sessions, name='group-booking-sessions'),
    path('group-booking/sessions/<int:session_id>/', views.group_booking_session_detail, name='group-booking-session-detail'),
    path('group-booking/sessions/<int:session_id>/assign-seats/', views.group_booking_assign_seats, name='group-booking-assign-seats'),
    path('group-booking/sessions/<int:session_id>/manual-split/', views.group_booking_manual_split, name='group-booking-manual-split'),
    path('group-booking/sessions/<int:session_id>/payments/initiate/', views.group_booking_initiate_payment, name='group-booking-initiate-payment'),
    path('group-booking/sessions/<int:session_id>/payments/<int:payment_id>/complete/', views.group_booking_complete_payment, name='group-booking-complete-payment'),
    path('group-booking/sessions/<int:session_id>/drop-out/', views.group_booking_drop_out, name='group-booking-drop-out'),
    path('group-booking/sessions/<int:session_id>/cancel/', views.group_booking_cancel, name='group-booking-cancel'),
    path('group-booking/invite/<str:invite_code>/', views.group_booking_session_by_invite, name='group-booking-session-by-invite'),
    path('group-booking/invite/<str:invite_code>/join/', views.group_booking_join, name='group-booking-join'),
    path('cinemas/', views.list_cinemas, name='cinema-list'),
    path('booking/cinemas/', views.booking_cinemas, name='booking-cinemas'),
    path('booking/movies/', views.booking_movies, name='booking-movies'),
    path('booking/dates/', views.booking_dates, name='booking-dates'),
    path('booking/times/', views.booking_times, name='booking-times'),
    path('booking/seat-layout/', views.booking_seat_layout, name='booking-seat-layout'),
    path('booking/available-seats/', views.booking_available_seats, name='booking-available-seats'),
    path('booking/dynamic-price/', views.booking_dynamic_price, name='booking-dynamic-price'),
    path('booking/ticket-price/', views.booking_ticket_price, name='booking-ticket-price'),
    path('booking/price-preview/', views.booking_price_preview, name='booking-price-preview'),
    path('booking/coupon/apply/', views.booking_apply_coupon, name='booking-coupon-apply'),
    path('booking/seat-reserve/', views.booking_seat_reserve, name='booking-seat-reserve'),
    path('booking/seat-release/', views.booking_seat_release, name='booking-seat-release'),
    path('booking/resume-notification/', views.booking_resume_notification, name='booking-resume-notification'),
    path('booking/sold-seats/', views.booking_sold_seats, name='booking-sold-seats'),
    path('booking/food-orders/', views.booking_food_orders, name='booking-food-orders'),
    path('booking/food-orders/<int:order_id>/', views.booking_food_order_detail, name='booking-food-order-detail'),
    path('food-items/', views.food_items, name='food-item-list'),
    path('combos/', views.combos, name='combo-list'),
    path('vendor/food-items/', views.vendor_food_items, name='vendor-food-items'),
    path('vendor/food-items/<int:item_id>/', views.vendor_food_item_detail, name='vendor-food-item-detail'),
    path('vendor/combos/', views.vendor_combos, name='vendor-combos'),
    path('vendor/combos/<int:combo_id>/', views.vendor_combo_detail, name='vendor-combo-detail'),
    path('vendor/seat-layout/', views.vendor_seat_layout, name='vendor-seat-layout'),
    path('vendor/seat-status/', views.vendor_seat_status, name='vendor-seat-status'),
    path('vendor/halls/', views.vendor_halls, name='vendor-halls'),
    path('vendor/pricing-rules/', views.vendor_pricing_rules, name='vendor-pricing-rules'),
    path('vendor/pricing-rules/<int:rule_id>/', views.vendor_pricing_rule_detail, name='vendor-pricing-rule-detail'),
    path('vendor/show-base-prices/', views.vendor_show_base_prices, name='vendor-show-base-prices'),
    path('vendor/loyalty/rules/', views.vendor_loyalty_rule, name='vendor-loyalty-rule'),
    path('vendor/loyalty/rewards/', views.vendor_loyalty_rewards, name='vendor-loyalty-rewards'),
    path('vendor/loyalty/rewards/<int:reward_id>/', views.vendor_loyalty_reward_detail, name='vendor-loyalty-reward-detail'),
    path('vendor/loyalty/promotions/', views.vendor_loyalty_promotions, name='vendor-loyalty-promotions'),
    path('vendor/loyalty/promotions/<int:promotion_id>/', views.vendor_loyalty_promotion_detail, name='vendor-loyalty-promotion-detail'),
    path('vendor/subscriptions/plans/', views.vendor_subscription_plans, name='vendor-subscription-plans'),
    path('vendor/subscriptions/plans/<int:plan_id>/', views.vendor_subscription_plan_detail, name='vendor-subscription-plan-detail'),
    path('vendor/offers/', views.vendor_offers, name='vendor-offers'),
    path('vendor/offers/<int:offer_id>/', views.vendor_offer_detail, name='vendor-offer-detail'),
    path('vendor/ticket-validation/scan/', views.validate_ticket_scan, name='vendor-ticket-validation-scan'),
    path('vendor/ticket-validation/monitor/', views.vendor_ticket_validation_monitor, name='vendor-ticket-validation-monitor'),
    path('vendor/ticket-validation/monitor/export/', views.vendor_ticket_validation_monitor_export, name='vendor-ticket-validation-monitor-export'),
    path('vendor/ticket-validation/monitor/export/jobs/', views.vendor_ticket_validation_monitor_export_jobs, name='vendor-ticket-validation-monitor-export-jobs'),
    path('vendor/ticket-validation/monitor/export/jobs/<int:job_id>/', views.vendor_ticket_validation_monitor_export_job_detail, name='vendor-ticket-validation-monitor-export-job-detail'),
    path('vendor/ticket-validation/monitor/export/jobs/<int:job_id>/download/', views.vendor_ticket_validation_monitor_export_job_download, name='vendor-ticket-validation-monitor-export-job-download'),
    path('vendor/wallet/', views.vendor_wallet_balance, name='vendor-wallet-balance'),
    path('vendor/cancellation-policy/', views.vendor_cancellation_policy, name='vendor-cancellation-policy'),
    path('vendor/wallet/withdraw/', views.vendor_wallet_withdraw, name='vendor-wallet-withdraw'),
    path('vendor/wallet/payout-profile/', views.vendor_payout_profile, name='vendor-payout-profile'),
    path('vendor/wallet/payout-profile/request-verification/', views.vendor_payout_profile_request_verification, name='vendor-payout-profile-request-verification'),
    path('vendor/wallet/payout-profile/verify/', views.vendor_payout_profile_verify, name='vendor-payout-profile-verify'),
    path('vendor/wallet/transactions/', views.vendor_wallet_transactions, name='vendor-wallet-transactions'),
    path('vendor/analytics/', views.vendor_analytics, name='vendor-analytics'),
    path('vendor/revenue/analytics/', views.vendor_revenue_analytics, name='vendor-revenue-analytics'),
    path('vendor/revenue/transactions/', views.vendor_revenue_transactions, name='vendor-revenue-transactions'),
    path('vendor/revenue/reports/', views.vendor_revenue_report, name='vendor-revenue-reports'),
    path('private-screening-requests/', views.private_screening_request_submit, name='private-screening-request-submit'),
    path('vendor/private-screening-requests/', views.vendor_private_screening_requests, name='vendor-private-screening-requests'),
    path('vendor/private-screening-requests/<int:request_id>/', views.vendor_private_screening_request_detail, name='vendor-private-screening-request-detail'),
    path('vendor/bulk-ticket-batches/', views.vendor_bulk_ticket_batches, name='vendor-bulk-ticket-batches'),
    path('vendor/bulk-ticket-batches/<int:batch_id>/export/', views.vendor_bulk_ticket_batch_export, name='vendor-bulk-ticket-batch-export'),
    path('vendor/promo-codes/', views.vendor_promo_codes, name='vendor-promo-codes'),
    path('vendor/promo-codes/<int:promo_id>/', views.vendor_promo_code_detail, name='vendor-promo-code-detail'),
    path('vendor/campaigns/', views.vendor_campaigns, name='vendor-campaigns'),
    path('vendor/campaigns/<int:campaign_id>/', views.vendor_campaign_detail, name='vendor-campaign-detail'),
    path('vendor/staff/', views.vendor_staff_accounts, name='vendor-staff-accounts'),
    path('vendor/staff/<int:staff_id>/', views.vendor_staff_account_detail, name='vendor-staff-account-detail'),
    path('movies/', views.movies, name='movie-list'),
    path('movies/<int:movie_id>/', views.movie_detail, name='movie-detail'),
    path('movies/slug/<slug:slug>/', views.movie_detail_by_slug, name='movie-detail-slug'),
    path('movies/<int:movie_id>/reviews/', views.movie_reviews, name='movie-reviews'),
    path('person/<slug:slug>/', views.person_detail, name='person-detail'),
    path('trailers/', views.trailers, name='trailer-list'),
    path('shows/', views.shows, name='show-list'),
    path('shows/<int:show_id>/', views.show_detail, name='show-detail'),
    path('vendor/shows/<int:show_id>/quick-hall-swap/', views.vendor_quick_hall_swap, name='vendor-quick-hall-swap'),
    path('auth/forgot-password/', views.forgot_password, name='forgot-password'),
    path('auth/verify-otp/', views.verify_otp, name='verify-otp'),
    path('auth/reset-password/', views.reset_password, name='reset-password'),
    path('profile/<int:user_id>/', views.update_profile, name='profile-update'),
    path('profile/admin/<int:admin_id>/', views.update_admin_profile, name='admin-profile-update'),
    path('profile/vendor/<int:vendor_id>/', views.update_vendor_profile, name='vendor-profile-update'),
    path('notifications/', views.notifications, name='notifications'),
    path('admin/notifications/custom-email/', views.admin_vendor_custom_email, name='admin-vendor-custom-email'),
    path('vendor/notifications/custom-email/', views.vendor_customer_custom_email, name='vendor-customer-custom-email'),
    path('payment/qr/', views.create_payment_qr, name='payment-qr'),
    path('payment/esewa/initiate/', views.esewa_initiate, name='payment-esewa-initiate'),
    path('payment/esewa/verify/', views.esewa_verify, name='payment-esewa-verify'),
    path('payment/esewa/callback/success/', views.esewa_callback_success, name='payment-esewa-callback-success'),
    path('payment/esewa/callback/failure/', views.esewa_callback_failure, name='payment-esewa-callback-failure'),
    path('ticket/<str:reference>/download/', views.download_ticket, name='ticket-download'),
    path('ticket/<str:reference>/details/', views.ticket_details, name='ticket-details'),
]

urlpatterns += router.urls
