# Generated by Django 4.2.27 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="admin_profiles/"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="vendor_profiles/"),
        ),
    ]
