# Generated by Django 4.2.27 on 2026-03-21 08:03

import django.core.validators
from django.db import migrations, models


def sync_banner_columns_if_needed(apps, schema_editor):
    """Safely align banner table columns across inconsistent DB states."""
    table_name = "banners"
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        # SQLite has limited alter-table support for drop column in older versions.
        return

    with schema_editor.connection.cursor() as cursor:
        existing_tables = set(schema_editor.connection.introspection.table_names(cursor))
        if table_name not in existing_tables:
            return

        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    table = schema_editor.quote_name(table_name)
    legacy_columns = [
        "background_image",
        "badge_text",
        "badge_type",
        "button_link",
        "button_text",
        "description",
        "meta_info",
        "poster_image",
        "subtitle",
        "title",
    ]
    for column in legacy_columns:
        if column in columns:
            schema_editor.execute(
                f"ALTER TABLE {table} DROP COLUMN {schema_editor.quote_name(column)}"
            )

    if "banner_type" not in columns:
        schema_editor.execute(
            f"ALTER TABLE {table} ADD COLUMN {schema_editor.quote_name('banner_type')} VARCHAR(10) NOT NULL DEFAULT 'PROMO'"
        )
    if "image" not in columns:
        schema_editor.execute(
            f"ALTER TABLE {table} ADD COLUMN {schema_editor.quote_name('image')} VARCHAR(100) NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_fooditem_vendor_hall'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    sync_banner_columns_if_needed,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='banner',
                    name='background_image',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='badge_text',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='badge_type',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='button_link',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='button_text',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='meta_info',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='poster_image',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='subtitle',
                ),
                migrations.RemoveField(
                    model_name='banner',
                    name='title',
                ),
                migrations.AddField(
                    model_name='banner',
                    name='banner_type',
                    field=models.CharField(choices=[('MOVIE', 'Movie'), ('PROMO', 'Promo')], default='PROMO', max_length=10),
                ),
                migrations.AddField(
                    model_name='banner',
                    name='image',
                    field=models.ImageField(blank=True, null=True, upload_to='banners/'),
                ),
                migrations.AlterField(
                    model_name='banner',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='moviecredit',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='person',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='review',
                    name='rating',
                    field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
                ),
            ],
        ),
    ]
