# Generated by Django 4.2.27 on 2026-04-05 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_secure_ticket_validation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=20, unique=True)),
                ('points_per_currency_unit', models.DecimalField(decimal_places=2, default=10, help_text='Currency amount required to earn one point.', max_digits=10)),
                ('redemption_value_per_point', models.DecimalField(decimal_places=2, default=1, help_text='Monetary value of one redeemed point.', max_digits=10)),
                ('first_booking_bonus', models.PositiveIntegerField(default=50)),
                ('points_expiry_months', models.PositiveIntegerField(default=12)),
                ('tier_silver_threshold', models.PositiveIntegerField(default=0)),
                ('tier_gold_threshold', models.PositiveIntegerField(default=1500)),
                ('tier_platinum_threshold', models.PositiveIntegerField(default=5000)),
                ('referral_bonus_points', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_program_configs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_type', models.CharField(choices=[('FESTIVAL', 'Festival'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('REFERRAL', 'Referral')], default='FESTIVAL', max_length=20)),
                ('trigger_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('bonus_flat_points', models.PositiveIntegerField(default=0)),
                ('stackable', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_promotions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('EXPIRE', 'Expire'), ('REVERSE_EARN', 'Reverse Earn'), ('RESTORE', 'Restore'), ('ADJUST', 'Adjust')], max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('reference_type', models.CharField(choices=[('BOOKING', 'Booking'), ('REWARD', 'Reward'), ('PROMOTION', 'Promotion'), ('REFERRAL', 'Referral'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=80, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREE_TICKET', 'Free Ticket'), ('CASHBACK', 'Cashback')], default='DISCOUNT', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stackable_with_coupon', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('USED', 'Used'), ('UNUSED', 'Unused'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='UNUSED', max_length=20)),
                ('redemption_code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reward_redemptions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserLoyaltyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_loyalty_wallets',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorLoyaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_currency_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Currency amount required to earn one point for this vendor.', max_digits=10, null=True)),
                ('first_booking_bonus', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendor_loyalty_rules',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='bookingdropoffevent',
            new_name='booking_dro_stage_ef67d6_idx',
            old_name='booking_drop_stage_58e8ef_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingdropoffevent',
            new_name='booking_dro_vendor__e5b29a_idx',
            old_name='booking_drop_vendor__ef02ee_idx',
        ),
        migrations.RenameIndex(
            model_name='bookingdropoffevent',
            new_name='booking_dro_transac_b69392_idx',
            old_name='booking_drop_transac_3dd915_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='loyalty_points_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Booking'), ('PAYMENT_SUCCESS', 'Payment Success'), ('SHOW_UPDATE', 'Show Update'), ('MARKETING_CAMPAIGN', 'Marketing Campaign'), ('BOOKING_CANCEL_REQUEST', 'Booking Cancel Request'), ('BOOKING_RESUME_PENDING', 'Booking Resume Pending'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('REFUND_PROCESSED', 'Refund Processed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BOOKING_EARNING', 'Booking Earning'), ('BOOKING_REVERSAL', 'Booking Earning Reversal'), ('PLATFORM_COMMISSION', 'Platform Commission'), ('PLATFORM_COMMISSION_REVERSAL', 'Platform Commission Reversal'), ('WITHDRAWAL_REQUEST', 'Withdrawal Request'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendorloyaltyrule',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rule', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='userloyaltywallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_wallet', to='app.user'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions', to='app.booking'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='app.reward'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='app.user'),
        ),
        migrations.AddField(
            model_name='reward',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='app.user'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.userloyaltywallet'),
        ),
        migrations.AddField(
            model_name='loyaltypromotion',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_promotions', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reward_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_reward_redemptions', to='app.rewardredemption'),
        ),
        migrations.AddIndex(
            model_name='userloyaltywallet',
            index=models.Index(fields=['tier'], name='user_loyalt_tier_3c14f2_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['user', 'status'], name='reward_rede_user_id_cee4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['reward', 'status'], name='reward_rede_reward__89996b_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['expires_at'], name='reward_rede_expires_5dd9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['is_active', 'expiry_date'], name='rewards_is_acti_835fba_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['vendor', 'is_active'], name='rewards_vendor__959531_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['points_required'], name='rewards_points__36ce72_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['user', 'transaction_type', 'created_at'], name='loyalty_tra_user_id_3de796_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='loyalty_tra_referen_eb9810_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['expires_at', 'is_expired'], name='loyalty_tra_expires_4fcd18_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypromotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='loyalty_pro_is_acti_d343b1_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypromotion',
            index=models.Index(fields=['vendor', 'is_active'], name='loyalty_pro_vendor__03d3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypromotion',
            index=models.Index(fields=['trigger_code'], name='loyalty_pro_trigger_df32c7_idx'),
        ),
    ]
