# Generated by Django 4.2.27 on 2026-04-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_loyaltyprogramconfig_loyaltypromotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='referral_wallet_refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='referral_wallet_used_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_device_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReferralWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expired', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_wallet', to='app.user')),
            ],
            options={
                'db_table': 'referral_wallets',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REWARDED', 'Rewarded'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('signup_ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('signup_user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('signup_device_fingerprint', models.CharField(blank=True, max_length=128, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='app.user')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='app.user')),
                ('reward_trigger_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_referrals', to='app.booking')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('EXPIRE', 'Expire'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='COMPLETED', max_length=20)),
                ('reason', models.CharField(choices=[('REFERRER_REWARD', 'Referrer Reward'), ('REFERRED_REWARD', 'Referred User Reward'), ('BOOKING_WALLET_USE', 'Booking Wallet Use'), ('BOOKING_WALLET_REFUND', 'Booking Wallet Refund'), ('REFERRAL_CANCELLATION_REVERSAL', 'Referral Cancellation Reversal'), ('EXPIRY', 'Expiry'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_wallet_transactions', to='app.booking')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='app.user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.referralwallet')),
            ],
            options={
                'db_table': 'referral_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='referral_tr_user_id_4e86ba_idx'), models.Index(fields=['booking', 'status'], name='referral_tr_booking_5bb2d7_idx'), models.Index(fields=['referral', 'status'], name='referral_tr_referra_528a06_idx'), models.Index(fields=['expires_at', 'status'], name='referral_tr_expires_eecb88_idx'), models.Index(fields=['reason', 'created_at'], name='referral_tr_reason_230fca_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='referrals_referra_3eadcc_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'created_at'], name='referrals_status_918a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='referrals_referre_cefb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred_user', 'status'], name='referrals_referre_5cac68_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['expires_at', 'status'], name='referrals_expires_8e3eb5_idx'),
        ),
    ]
