# Generated by Django 4.2.27 on 2026-04-05 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_booking_referral_wallet_refunded_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('split_mode', models.CharField(choices=[('EQUAL', 'Equal Split'), ('MANUAL', 'Manual Split'), ('SEAT_BASED', 'Seat Based')], default='EQUAL', max_length=20)),
                ('selected_seats', models.JSONField(blank=True, default=list)),
                ('seat_price_map', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIALLY_PAID', 'Partially Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_booking_sessions_hosted', to='app.user')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_booking_sessions', to='app.show')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_booking_sessions', to='app.showtime')),
            ],
            options={
                'db_table': 'group_booking_sessions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('selected_seats', models.JSONField(blank=True, default=list)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('LEFT', 'Left')], default='PENDING', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.groupbookingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_booking_participations', to='app.user')),
            ],
            options={
                'db_table': 'group_booking_participants',
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='ESEWA', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_payments', to='app.booking')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.groupparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.groupbookingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_payments', to='app.user')),
            ],
            options={
                'db_table': 'group_payments',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session', 'status'], name='group_payme_session_b86e2d_idx'), models.Index(fields=['participant', 'status'], name='group_payme_partici_223261_idx'), models.Index(fields=['user', 'status'], name='group_payme_user_id_b92409_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='groupparticipant',
            index=models.Index(fields=['session', 'payment_status'], name='group_booki_session_0d4131_idx'),
        ),
        migrations.AddIndex(
            model_name='groupparticipant',
            index=models.Index(fields=['user', 'payment_status'], name='group_booki_user_id_32c66c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupbookingsession',
            index=models.Index(fields=['status', 'expires_at'], name='group_booki_status_975b21_idx'),
        ),
        migrations.AddIndex(
            model_name='groupbookingsession',
            index=models.Index(fields=['host', 'status'], name='group_booki_host_id_8829a4_idx'),
        ),
        migrations.AddIndex(
            model_name='groupbookingsession',
            index=models.Index(fields=['showtime', 'status'], name='group_booki_showtim_c609b3_idx'),
        ),
    ]
