# Generated by Django 4.2.27 on 2026-04-05 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_groupbookingsession_groupparticipant_grouppayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='SILVER', max_length=20)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('discount_type', models.CharField(choices=[('NONE', 'None'), ('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], default='NONE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_tickets_total', models.PositiveIntegerField(default=0)),
                ('early_access_hours', models.PositiveIntegerField(default=0)),
                ('special_pricing_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subscription_only_access', models.BooleanField(default=False)),
                ('allow_multiple_active', models.BooleanField(default=False)),
                ('is_stackable_with_coupon', models.BooleanField(default=True)),
                ('is_stackable_with_loyalty', models.BooleanField(default=True)),
                ('is_stackable_with_referral_wallet', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='app.vendor')),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['priority', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription_free_tickets_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('NEW_BOOKING', 'New Booking'), ('PAYMENT_SUCCESS', 'Payment Success'), ('SHOW_UPDATE', 'Show Update'), ('MARKETING_CAMPAIGN', 'Marketing Campaign'), ('BOOKING_CANCEL_REQUEST', 'Booking Cancel Request'), ('BOOKING_RESUME_PENDING', 'Booking Resume Pending'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('REFUND_PROCESSED', 'Refund Processed'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment')], default='ACTIVE', max_length=20)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_free_tickets', models.PositiveIntegerField(default=0)),
                ('used_free_tickets', models.PositiveIntegerField(default=0)),
                ('total_discount_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='app.subscriptionplan')),
                ('upgraded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_children', to='app.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.user')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='app.vendor')),
            ],
            options={
                'db_table': 'user_subscriptions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade'), ('PRORATION', 'Proration'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('FREE_TICKET_APPLIED', 'Free Ticket Applied'), ('REFUND', 'Refund'), ('CANCEL', 'Cancel'), ('EXPIRE', 'Expire')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_tickets_used', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_transactions', to='app.booking')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to='app.user')),
            ],
            options={
                'db_table': 'subscription_transactions',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.usersubscription'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', 'end_at'], name='user_subscr_user_id_952410_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['vendor', 'status', 'end_at'], name='user_subscr_vendor__8d57b6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan', 'status'], name='user_subscr_plan_id_121348_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'end_at'], name='user_subscr_status_f39153_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_7d000e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_c700d3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['booking', 'transaction_type'], name='subscriptio_booking_a82c07_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='subscriptio_transac_0ee955_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['vendor', 'is_active'], name='subscriptio_vendor__fd0aec_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['tier', 'is_active'], name='subscriptio_tier_8542f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['is_public', 'is_active'], name='subscriptio_is_publ_f75f03_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['valid_from', 'valid_until'], name='subscriptio_valid_f_0e6976_idx'),
        ),
    ]
