# Generated by Django 4.2.27 on 2026-04-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_dynamic_pricing_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='pricing_rul_vendor__9bcb8f_idx',
            old_name='pricing_rul_vendor__cab3e4_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='pricing_rul_is_acti_ff4135_idx',
            old_name='pricing_rul_is_acti_608570_idx',
        ),
        migrations.RenameIndex(
            model_name='pricingrule',
            new_name='pricing_rul_movie_i_ceb32c_idx',
            old_name='pricing_rul_movie_i_2da287_idx',
        ),
        migrations.RenameIndex(
            model_name='showbaseprice',
            new_name='show_base_p_show_id_7c9cc0_idx',
            old_name='show_base_p_show_id_73ab50_idx',
        ),
        migrations.RenameIndex(
            model_name='showbaseprice',
            new_name='show_base_p_seat_ca_f78b04_idx',
            old_name='show_base_p_seat_ca_a4dcae_idx',
        ),
    ]
