# Generated by Django 4.2.27 on 2026-04-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_backgroundjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__status_d47efd_idx',
            old_name='bg_job_status_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__job_typ_d149d7_idx',
            old_name='bg_job_type_created_idx',
        ),
    ]
