# Generated by Django 4.2.27 on 2026-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_bg_job_status_avail_idx_background__status_d47efd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fraud_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='fraud_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='fraud_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
