# Generated by Django 4.2.27 on 2026-04-05 13:30

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def forwards_migrate_role_control_data(apps, schema_editor):
    VendorOffer = apps.get_model("app", "VendorOffer")
    ReferralPolicy = apps.get_model("app", "ReferralPolicy")
    VendorPromoCode = apps.get_model("app", "VendorPromoCode")
    Reward = apps.get_model("app", "Reward")
    LoyaltyPromotion = apps.get_model("app", "LoyaltyPromotion")
    SubscriptionPlan = apps.get_model("app", "SubscriptionPlan")

    ReferralPolicy.objects.get_or_create(
        key="default",
        defaults={
            "referrer_reward_amount": Decimal("100.00"),
            "referred_reward_amount": Decimal("50.00"),
            "reward_expiry_days": 90,
            "wallet_cap_percent": Decimal("20.00"),
            "max_signups_per_ip_per_day": 3,
            "max_signups_per_device_per_day": 2,
            "auto_approve_rewards": True,
            "is_active": True,
        },
    )

    for promo in VendorPromoCode.objects.all().iterator():
        VendorOffer.objects.get_or_create(
            vendor_id=promo.vendor_id,
            offer_type="PROMO",
            code=promo.code,
            defaults={
                "title": promo.title,
                "description": promo.description,
                "discount_type": promo.discount_type,
                "discount_value": promo.discount_value,
                "min_booking_amount": promo.min_booking_amount,
                "allow_loyalty_redemption": True,
                "subscriber_perk_text": None,
                "starts_at": promo.valid_from,
                "ends_at": promo.valid_until,
                "is_active": promo.is_active,
                "metadata": {
                    "source": "vendor_promo_code",
                    "source_id": promo.id,
                    "requires_student": bool(promo.requires_student),
                    "seat_category_scope": promo.seat_category_scope,
                    "allowed_weekdays": promo.allowed_weekdays,
                    "usage_limit": promo.usage_limit,
                    "per_user_limit": promo.per_user_limit,
                    "is_flash_sale": bool(promo.is_flash_sale),
                },
            },
        )

    for reward in Reward.objects.filter(vendor_id__isnull=False).iterator():
        VendorOffer.objects.get_or_create(
            vendor_id=reward.vendor_id,
            offer_type="LOYALTY",
            code=f"REWARD-{reward.id}",
            defaults={
                "title": reward.title,
                "description": reward.description,
                "discount_type": (
                    "PERCENTAGE"
                    if reward.discount_percent is not None and reward.discount_percent > 0
                    else ("FIXED" if reward.discount_amount is not None and reward.discount_amount > 0 else "NONE")
                ),
                "discount_value": reward.discount_percent or reward.discount_amount or Decimal("0.00"),
                "min_booking_amount": Decimal("0.00"),
                "allow_loyalty_redemption": bool(reward.is_stackable_with_coupon),
                "subscriber_perk_text": None,
                "starts_at": None,
                "ends_at": reward.expiry_date,
                "is_active": reward.is_active,
                "metadata": {
                    "source": "vendor_reward",
                    "source_id": reward.id,
                    "reward_type": reward.reward_type,
                    "points_required": int(reward.points_required or 0),
                    "stock_limit": reward.stock_limit,
                    "redeemed_count": int(reward.redeemed_count or 0),
                    "max_discount_amount": str(reward.max_discount_amount) if reward.max_discount_amount is not None else None,
                },
            },
        )

    for promotion in LoyaltyPromotion.objects.filter(vendor_id__isnull=False).iterator():
        trigger_code = (promotion.trigger_code or "").strip().upper()
        code = trigger_code or f"PROMOTION-{promotion.id}"
        VendorOffer.objects.get_or_create(
            vendor_id=promotion.vendor_id,
            offer_type="PERK",
            code=code,
            defaults={
                "title": promotion.title,
                "description": promotion.description,
                "discount_type": "NONE",
                "discount_value": Decimal("0.00"),
                "min_booking_amount": Decimal("0.00"),
                "allow_loyalty_redemption": True,
                "subscriber_perk_text": "Bonus loyalty multiplier campaign",
                "starts_at": promotion.starts_at,
                "ends_at": promotion.ends_at,
                "is_active": promotion.is_active,
                "metadata": {
                    "source": "vendor_loyalty_promotion",
                    "source_id": promotion.id,
                    "promo_type": promotion.promo_type,
                    "bonus_multiplier": str(promotion.bonus_multiplier),
                    "bonus_flat_points": int(promotion.bonus_flat_points or 0),
                    "stackable": bool(promotion.stackable),
                    "trigger_code": trigger_code,
                },
            },
        )

    for plan in SubscriptionPlan.objects.filter(vendor_id__isnull=False, is_public=True).iterator():
        metadata = dict(plan.metadata or {})
        metadata["migrated_to_admin_control"] = True
        metadata["legacy_scope"] = "VENDOR"
        plan.metadata = metadata
        plan.is_public = False
        plan.save(update_fields=["metadata", "is_public", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_booking_fraud_level_booking_fraud_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default="default", max_length=20, unique=True)),
                ("referrer_reward_amount", models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ("referred_reward_amount", models.DecimalField(decimal_places=2, default=50, max_digits=12)),
                ("reward_expiry_days", models.PositiveIntegerField(default=90)),
                ("wallet_cap_percent", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("max_signups_per_ip_per_day", models.PositiveIntegerField(default=3)),
                ("max_signups_per_device_per_day", models.PositiveIntegerField(default=2)),
                ("auto_approve_rewards", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "referral_policies",
            },
        ),
        migrations.CreateModel(
            name="VendorOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("offer_type", models.CharField(choices=[("PROMO", "Promo"), ("BUNDLE", "Bundle"), ("PERK", "Perk"), ("LOYALTY", "Loyalty")], default="PROMO", max_length=20)),
                ("discount_type", models.CharField(choices=[("NONE", "None"), ("PERCENTAGE", "Percentage"), ("FIXED", "Fixed")], default="NONE", max_length=20)),
                ("discount_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("min_booking_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("allow_loyalty_redemption", models.BooleanField(default=True)),
                ("subscriber_perk_text", models.CharField(blank=True, max_length=200, null=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="app.vendor")),
            ],
            options={
                "db_table": "vendor_offers",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="vendoroffer",
            index=models.Index(fields=["vendor", "is_active"], name="vendor_offe_vendor__8212da_idx"),
        ),
        migrations.AddIndex(
            model_name="vendoroffer",
            index=models.Index(fields=["offer_type", "is_active"], name="vendor_offe_offer_t_4e1ae7_idx"),
        ),
        migrations.AddIndex(
            model_name="vendoroffer",
            index=models.Index(fields=["starts_at", "ends_at"], name="vendor_offe_starts__fbff89_idx"),
        ),
        migrations.AddConstraint(
            model_name="vendoroffer",
            constraint=models.UniqueConstraint(condition=models.Q(("code__isnull", False)), fields=("vendor", "code"), name="unique_vendor_offer_code_when_present"),
        ),
        migrations.RunPython(forwards_migrate_role_control_data, migrations.RunPython.noop),
    ]
