# Generated by Django 4.2.27 on 2026-04-05 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_vendoroffer_referralpolicy_and_role_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRule',
            fields=[
            ],
            options={
                'verbose_name': 'Loyalty Rule',
                'verbose_name_plural': 'Loyalty Rules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.loyaltyprogramconfig',),
        ),
        migrations.RenameIndex(
            model_name='vendoroffer',
            new_name='vendor_offe_vendor__a1b071_idx',
            old_name='vendor_offe_vendor__8212da_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoroffer',
            new_name='vendor_offe_offer_t_b5a955_idx',
            old_name='vendor_offe_offer_t_4e1ae7_idx',
        ),
        migrations.RenameIndex(
            model_name='vendoroffer',
            new_name='vendor_offe_starts__3d6d14_idx',
            old_name='vendor_offe_starts__fbff89_idx',
        ),
        migrations.AlterField(
            model_name='referralpolicy',
            name='wallet_cap_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
