# Generated by Django 4.2.27 on 2026-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_loyaltyrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_wallet', to='app.user')),
            ],
            options={
                'db_table': 'user_wallets',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOPUP', 'Top Up'), ('DEBIT', 'Debit'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('provider', models.CharField(default='SYSTEM', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_wallet_transactions', to='app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_transactions', to='app.user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.userwallet')),
            ],
            options={
                'db_table': 'user_wallet_transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['user', 'status', 'created_at'], name='user_wallet_user_id_3430cd_idx'),
                    models.Index(fields=['reference_id'], name='user_wallet_referen_3fb79e_idx'),
                    models.Index(fields=['transaction_type', 'created_at'], name='user_wallet_transac_da5779_idx'),
                ],
            },
        ),
    ]
