# Generated by Django 4.2.27 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_user_wallet_topup"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="is_veg",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="item_image",
            field=models.ImageField(blank=True, null=True, upload_to="food_items/"),
        ),
    ]