# Generated by Django 4.2.27 on 2026-04-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_payment_transaction_uuid_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('refund_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'refund_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReversalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reversal_type', models.CharField(choices=[('BOOKING_EARNING', 'Booking Earning'), ('PLATFORM_COMMISSION', 'Platform Commission'), ('REFUND', 'Refund'), ('WITHDRAWAL', 'Withdrawal')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('reversal_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reversal_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorCommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('EARNED', 'Earned'), ('REVERSED', 'Reversed')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'vendor_commission_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decision_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='REQUESTED', max_length=20)),
                ('payout_reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'withdrawal_ledger_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='approval_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movie',
            name='approval_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movies', to='app.admin'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_vendor_transactions', to='app.admin'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decision_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='adminwallettransaction',
            index=models.Index(fields=['status', 'created_at'], name='admin_walle_status_c9656d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'booking_date'], name='bookings_booking_bdd300_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['approval_status', 'created_at'], name='movies_approva_79717e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_approved', 'created_at'], name='movies_is_appr_f8edf2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', 'payment_date'], name='payments_payment_672dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'payment_date'], name='payments_booking_4b60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vendor', 'created_at'], name='transaction_vendor__a8f0db_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_94cf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_uuid'], name='transaction_transac_fcddff_idx'),
        ),
        migrations.AddIndex(
            model_name='userwallettransaction',
            index=models.Index(fields=['status', 'created_at'], name='user_wallet_status_4bb6cf_idx'),
        ),
        migrations.AddField(
            model_name='withdrawalledger',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_ledger_decisions', to='app.admin'),
        ),
        migrations.AddField(
            model_name='withdrawalledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_ledger_entries', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='withdrawalledger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_ledger_entries', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='withdrawalledger',
            name='withdrawal_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_ledger_entries', to='app.transaction'),
        ),
        migrations.AddField(
            model_name='vendorcommissionledger',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_ledger_entries', to='app.booking'),
        ),
        migrations.AddField(
            model_name='vendorcommissionledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_ledger_entries', to='app.payment'),
        ),
        migrations.AddField(
            model_name='vendorcommissionledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger_entries', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='vendorcommissionledger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ledger_entries', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='reversalledger',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_ledger_entries', to='app.booking'),
        ),
        migrations.AddField(
            model_name='reversalledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_ledger_entries', to='app.payment'),
        ),
        migrations.AddField(
            model_name='reversalledger',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_ledger_entries', to='app.refund'),
        ),
        migrations.AddField(
            model_name='reversalledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_ledger_entries', to='app.vendor'),
        ),
        migrations.AddField(
            model_name='reversalledger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_ledger_entries', to='app.wallet'),
        ),
        migrations.AddField(
            model_name='refundledger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ledger_entries', to='app.booking'),
        ),
        migrations.AddField(
            model_name='refundledger',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ledger_entries', to='app.payment'),
        ),
        migrations.AddField(
            model_name='refundledger',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='app.refund'),
        ),
        migrations.AddField(
            model_name='refundledger',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ledger_entries', to='app.vendor'),
        ),
        migrations.AddIndex(
            model_name='withdrawalledger',
            index=models.Index(fields=['vendor', 'created_at'], name='withdrawal__vendor__503446_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalledger',
            index=models.Index(fields=['wallet', 'created_at'], name='withdrawal__wallet__087492_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalledger',
            index=models.Index(fields=['withdrawal_transaction', 'created_at'], name='withdrawal__withdra_6f95f4_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalledger',
            index=models.Index(fields=['status', 'created_at'], name='withdrawal__status_83e552_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalledger',
            index=models.Index(fields=['payout_reference'], name='withdrawal__payout__3ffcec_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcommissionledger',
            index=models.Index(fields=['vendor', 'created_at'], name='vendor_comm_vendor__d68efa_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcommissionledger',
            index=models.Index(fields=['booking', 'created_at'], name='vendor_comm_booking_a5166f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcommissionledger',
            index=models.Index(fields=['payment', 'created_at'], name='vendor_comm_payment_4109fe_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcommissionledger',
            index=models.Index(fields=['entry_type', 'created_at'], name='vendor_comm_entry_t_256646_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcommissionledger',
            index=models.Index(fields=['status', 'created_at'], name='vendor_comm_status_d5fadb_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['vendor', 'created_at'], name='reversal_le_vendor__3b97e2_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['booking', 'created_at'], name='reversal_le_booking_21debd_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['payment', 'created_at'], name='reversal_le_payment_5c0890_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['refund', 'created_at'], name='reversal_le_refund__51efd6_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['reversal_type', 'created_at'], name='reversal_le_reversa_2b71a0_idx'),
        ),
        migrations.AddIndex(
            model_name='reversalledger',
            index=models.Index(fields=['status', 'created_at'], name='reversal_le_status_bbec4f_idx'),
        ),
        migrations.AddIndex(
            model_name='refundledger',
            index=models.Index(fields=['vendor', 'created_at'], name='refund_ledg_vendor__80715d_idx'),
        ),
        migrations.AddIndex(
            model_name='refundledger',
            index=models.Index(fields=['booking', 'created_at'], name='refund_ledg_booking_d1c9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='refundledger',
            index=models.Index(fields=['payment', 'created_at'], name='refund_ledg_payment_94c3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='refundledger',
            index=models.Index(fields=['refund', 'created_at'], name='refund_ledg_refund__b4c750_idx'),
        ),
        migrations.AddIndex(
            model_name='refundledger',
            index=models.Index(fields=['status', 'created_at'], name='refund_ledg_status_3a553f_idx'),
        ),
    ]
