# Generated by Django 4.2.27 on 2026-04-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_refundledger_reversalledger_vendorcommissionledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('NOTIFICATION_EMAIL', 'Notification Email'), ('NOTIFICATION_EMAIL_RETRY', 'Notification Email Retry'), ('ANALYTICS_MONITOR_EXPORT', 'Analytics Monitor Export'), ('GATEWAY_STATUS_CHECK', 'Gateway Status Check'), ('FINANCIAL_SUMMARY_ROLLUP', 'Financial Summary Rollup'), ('WITHDRAWAL_SETTLEMENT', 'Withdrawal Settlement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalledger',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='REQUESTED', max_length=20),
        ),
    ]
