# Generated by Django 4.2.27 on 2026-04-11 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_bookingitem_vendorwallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.bookingseat',),
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor Wallet',
                'verbose_name_plural': 'Vendor Wallets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.wallet',),
        ),
        migrations.RenameIndex(
            model_name='adminwallettransaction',
            new_name='admin_walle_transac_a8fe64_idx',
            old_name='admin_walle_transac_4b08e2_idx',
        ),
        migrations.RenameIndex(
            model_name='adminwallettransaction',
            new_name='admin_walle_vendor__5d020e_idx',
            old_name='admin_walle_vendor__f4202c_idx',
        ),
        migrations.RenameIndex(
            model_name='adminwallettransaction',
            new_name='admin_walle_booking_8be093_idx',
            old_name='admin_walle_booking_8fb1c6_idx',
        ),
        migrations.RenameIndex(
            model_name='authsession',
            new_name='auth_sessio_role_62c350_idx',
            old_name='app_authses_role_0f7fa6_idx',
        ),
        migrations.RenameIndex(
            model_name='authsession',
            new_name='auth_sessio_role_439c0a_idx',
            old_name='app_authses_role_8b2185_idx',
        ),
        migrations.AlterField(
            model_name='platformrevenueconfig',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
