# Generated by Django 4.2.27 on 2026-04-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_bookingitem_vendorwallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('BANK', 'Bank Account'), ('UPI', 'UPI'), ('EWALLET', 'E-Wallet'), ('MOBILE', 'Mobile Wallet')], default='BANK', max_length=20)),
                ('destination_name', models.CharField(blank=True, max_length=120, null=True)),
                ('destination_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=120, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=120, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=120, null=True)),
                ('minimum_withdrawal_amount', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('payout_schedule', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20)),
                ('payout_schedule_days', models.JSONField(blank=True, default=list)),
                ('payout_schedule_time', models.TimeField(blank=True, null=True)),
                ('failed_retry_limit', models.PositiveIntegerField(default=3)),
                ('retry_backoff_minutes', models.PositiveIntegerField(default=60)),
                ('is_destination_verified', models.BooleanField(default=False)),
                ('destination_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verification_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='payout_profile', to='app.vendor')),
            ],
            options={
                'db_table': 'vendor_payout_profiles',
            },
        ),
    ]
