# Generated by Django 4.2.27 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_vendorpayoutprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpolicy',
            name='reward_hold_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
