# Generated by Django 4.2.27 on 2026-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_loyalty_tier_caps_and_abuse_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade'), ('PRORATION', 'Proration'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('FREE_TICKET_APPLIED', 'Free Ticket Applied'), ('REFUND', 'Refund'), ('CANCEL', 'Cancel'), ('PAUSE', 'Pause'), ('RESUME', 'Resume'), ('EXPIRE', 'Expire')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment')], default='ACTIVE', max_length=20),
        ),
    ]
