# Generated by Django 4.2.27 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_alter_subscriptiontransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("NOTIFICATION_EMAIL", "Notification Email"),
                    ("NOTIFICATION_EMAIL_RETRY", "Notification Email Retry"),
                    ("ANALYTICS_MONITOR_EXPORT", "Analytics Monitor Export"),
                    ("GATEWAY_STATUS_CHECK", "Gateway Status Check"),
                    ("FINANCIAL_SUMMARY_ROLLUP", "Financial Summary Rollup"),
                    ("WITHDRAWAL_SETTLEMENT", "Withdrawal Settlement"),
                    ("STALE_PENDING_CLEANUP", "Stale Pending Cleanup"),
                    ("DATA_RECONCILIATION", "Data Reconciliation"),
                    ("ANALYTICS_ROLLUP", "Analytics Rollup"),
                ],
                max_length=50,
            ),
        ),
    ]
